-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."AppneuronProducts"
(
    "Id" smallint NOT NULL,
    "ProductName" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."CustomerDemographics"
(
    "Id" smallint NOT NULL,
    "CustomerDesc" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."CustomerDiscounts"
(
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "DiscountId" smallint NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."CustomerProjectHasProducts"
(
    "Id" bigint NOT NULL,
    "ProductId" smallint NOT NULL,
    "ProjectId" bigint NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."CustomerProjects"
(
    "Id" bigint NOT NULL,
    "CustomerId" integer NOT NULL,
    "VoteId" smallint,
    "CreatedAt" date NOT NULL,
    "ProjectKey" character varying(500) NOT NULL,
    "ProjectName" character varying(20) NOT NULL,
    "ProjectBody" character varying(100),
    "Statuse" boolean NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."CustomerScales"
(
    "Id" smallint NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(100),
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Customers"
(
    "UserId" integer NOT NULL,
    "CustomerScaleId" smallint NOT NULL,
    "DemographicId" smallint,
    "DashboardKey" character varying(500) NOT NULL,
    "IndustryId" smallint NOT NULL,
    PRIMARY KEY ("UserId")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Discounts"
(
    "Id" smallint NOT NULL,
    "DiscountName" character varying(50) NOT NULL,
    "Percent" smallint NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."GamePlatforms"
(
    "Id" smallint NOT NULL,
    "PlatformName" character varying(50) NOT NULL,
    "PlatformDescription" character varying(100),
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Industries"
(
    "Id" smallint NOT NULL,
    "Name" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Invoices"
(
    "Id" bigint NOT NULL,
    "BillNo" character varying(500) NOT NULL,
    "CreatedAt" date NOT NULL,
    "LastPaymentTime" date NOT NULL,
    "UserId" integer NOT NULL,
    "DiscountId" smallint NOT NULL,
    "UnitPrice" integer NOT NULL,
    "IsItPaid" boolean NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Languages"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(10) NOT NULL,
    "Code" character varying(10) NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Logs"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "MessageTemplate" text,
    "Level" text,
    "TimeStamp" timestamp with time zone NOT NULL,
    "Exception" text,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."ProjectPlatforms"
(
    "Id" bigint NOT NULL,
    "ProjectId" bigint NOT NULL,
    "GamePlatformId" smallint NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Translates"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "LangId" integer NOT NULL,
    "Code" character varying(50) NOT NULL,
    "Value" character varying(500) NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Votes"
(
    "Id" smallint NOT NULL,
    "VoteName" character varying(50) NOT NULL,
    "VoteValue" smallint NOT NULL,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

ALTER TABLE public."CustomerDiscounts"
    ADD FOREIGN KEY ("DiscountId")
    REFERENCES public."Discounts" ("Id")
    NOT VALID;


ALTER TABLE public."CustomerDiscounts"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Customers" ("UserId")
    NOT VALID;


ALTER TABLE public."CustomerProjectHasProducts"
    ADD FOREIGN KEY ("ProductId")
    REFERENCES public."AppneuronProducts" ("Id")
    NOT VALID;


ALTER TABLE public."CustomerProjectHasProducts"
    ADD FOREIGN KEY ("ProjectId")
    REFERENCES public."CustomerProjects" ("Id")
    NOT VALID;


ALTER TABLE public."CustomerProjects"
    ADD FOREIGN KEY ("CustomerId")
    REFERENCES public."Customers" ("UserId")
    NOT VALID;


ALTER TABLE public."CustomerProjects"
    ADD FOREIGN KEY ("VoteId")
    REFERENCES public."Votes" ("Id")
    NOT VALID;


ALTER TABLE public."Customers"
    ADD FOREIGN KEY ("CustomerScaleId")
    REFERENCES public."CustomerScales" ("Id")
    NOT VALID;


ALTER TABLE public."Customers"
    ADD FOREIGN KEY ("DemographicId")
    REFERENCES public."CustomerDemographics" ("Id")
    NOT VALID;


ALTER TABLE public."Customers"
    ADD FOREIGN KEY ("IndustryId")
    REFERENCES public."Industries" ("Id")
    NOT VALID;


ALTER TABLE public."Invoices"
    ADD FOREIGN KEY ("DiscountId")
    REFERENCES public."Discounts" ("Id")
    NOT VALID;


ALTER TABLE public."ProjectPlatforms"
    ADD FOREIGN KEY ("GamePlatformId")
    REFERENCES public."GamePlatforms" ("Id")
    NOT VALID;


ALTER TABLE public."ProjectPlatforms"
    ADD FOREIGN KEY ("ProjectId")
    REFERENCES public."CustomerProjects" ("Id")
    NOT VALID;


ALTER TABLE public."Translates"
    ADD FOREIGN KEY ("LangId")
    REFERENCES public."Languages" ("Id")
    NOT VALID;

END;